version : '3'
services:
  mysql:
    image: mysql:8-oracle
    container_name: employeedb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=employeedb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpwd123
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1m30s
      timeout: 20s
      retries: 5
    ports:
      - "3307:3306"
    volumes:
      - "./generated/store/script.sql:/docker-entrypoint-initdb.d/1.sql"
