openapi: 3.0.1
info:
  title: Employees
  version: 0.1.0
servers:
- url: "{server}:{port}/employees"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /employees:
    post:
      operationId: postEmployees
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeInsert'
      responses:
        "500":
          description: InternalServerError
        "201":
          description: Created
        "409":
          description: Conflict
  /tasks:
    get:
      operationId: getTasks
      parameters:
      - name: empId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EmployeeTask'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /{taskId}:
    put:
      operationId: putTaskid
      parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeTaskUpdate'
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeTask'
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    EmployeeInsert:
      $ref: '#/components/schemas/Employee'
    ErrorPayload:
      type: object
      properties:
        reason:
          type: string
          description: Reason phrase
        path:
          type: string
          description: Request path
        method:
          type: string
          description: Method type of the request
        message:
          type: string
          description: Error message
        timestamp:
          type: string
          description: Timestamp of the error
        status:
          type: integer
          description: Relevant HTTP status code
          format: int32
    EmployeeTaskUpdate:
      type: object
      properties:
        taskName:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - COMPLETED
          - IN_PROGRESS
          - NOT_STARTED
        employeeId:
          type: integer
          format: int64
    Employee:
      required:
      - age
      - department
      - email
      - id
      - name
      - phone
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        age:
          type: integer
          format: int64
        phone:
          type: string
        email:
          type: string
        department:
          type: string
    EmployeeTaskInsert:
      $ref: '#/components/schemas/EmployeeTask'
    EmployeeTask:
      required:
      - description
      - employeeId
      - status
      - taskId
      - taskName
      type: object
      properties:
        taskId:
          type: integer
          format: int64
        taskName:
          type: string
        description:
          type: string
        status:
          type: string
          enum:
          - COMPLETED
          - IN_PROGRESS
          - NOT_STARTED
        employeeId:
          type: integer
          format: int64
